# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(463, 361)
        self.button_add = QtWidgets.QPushButton(Form)
        self.button_add.setGeometry(QtCore.QRect(120, 130, 191, 71))
        self.button_add.setObjectName("button_add")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ШАРИКИИИИИИИИИИИИИ"))
        self.button_add.setText(_translate("Form", "Нужно больше шариков"))
